name: 12 - Env Scopes

on: workflow_dispatch

env:
  NAME: Dina

jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: Uses workflow + job env
        run: |
          echo "my name is $NAME"
